
# Site settings
title: Lalith Sharan
description: Computer vision | Deep Learning | Healthcare
baseurl: "" # the subpath of your site, e.g. /blog
#url: 'https://lalithnag.github.io/' # production url
url: 'https://localhost:4000' #development url

# User settings
username: Lalith
user_description: Hello! 👋 I'm Lalith, a medical systems engineer focused on deep learning and computer vision for healthcare applications – in particular endoscopic image analysis. Feel free to check out the stuff I do and get in touch!
user_title: Computer vision | Deep Learning | Healthcare
email: reach.lalith@gmail.com
twitter_username: onyourseat
github_username:  lalithnag
gplus_username:  lalithnag

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
